{{ config(materialized = 'view') }}


-- THIS QUERY DEMONSTRATES RELATION BETWEEN POPULATIOON DENSITY AND COVID_CASES 

with population_density as (
    select data.PROVINCE, max(data.TOTAL_CASES_PER_MILLION) as MAX_TOTAL_CASES_PER_MILLION, min(data.TOTAL_CASES_PER_MILLION) as MIN_TOTAL_CASES_PER_MILLION
    from "INTERVIEW_DB"."PLAYGROUND_DIGAMBER_KALIVEMULA"."PROVINCES" as pro INNER JOIN 
    "INTERVIEW_DB"."PLAYGROUND_DIGAMBER_KALIVEMULA"."COVID19_DATA" as data on pro.PROVINCE = data.PROVINCE GROUP BY data.PROVINCE
)

select CAST(MAX_TOTAL_CASES_PER_MILLION as INT) - CAST(MIN_TOTAL_CASES_PER_MILLION as INT)/2 as cases_number , CAST(pro.POPULATION_DENSITY as INT) as population_density from population_density as cases INNER JOIN "INTERVIEW_DB"."PLAYGROUND_DIGAMBER_KALIVEMULA"."PROVINCES" as pro 
on pro.PROVINCE= cases.PROVINCE