{{ config(materialized = 'view') }}


-- THIS QUERY DEMONSTRATES RELATION BETWEEN POPULATIOON DENSITY AND COVID_CASES 

with population_density as (
    select data.PROVINCE, max(data.TOTAL_CASES_PER_MILLION) as MAX_TOTAL_CASES_PER_MILLION, min(data.TOTAL_CASES_PER_MILLION) as MIN_TOTAL_CASES_PER_MILLION
    from "INTERVIEW_DB"."PLAYGROUND_DIGAMBER_KALIVEMULA"."PROVINCES" as pro INNER JOIN 
    "INTERVIEW_DB"."PLAYGROUND_DIGAMBER_KALIVEMULA"."COVID19_DATA" as data on pro.PROVINCE = data.PROVINCE GROUP BY data.PROVINCE
)

select cases.*, pro.POPULATION_DENSITY from max_cases as cases INNER JOIN "INTERVIEW_DB"."PLAYGROUND_DIGAMBER_KALIVEMULA"."PROVINCES" as pro 
on pro.PROVINCE= cases.PROVINCE