{{ config(materialized = 'view') }}


-- THIS QUERY DEMONSTRATES RELATION BETWEEN POPULATIOON DENSITY AND COVID_CASES 

with recovery_rate as (
    select max(data.CASE_RECOVERED_RATE) as CASE_RECOVERED_RATE , data.PROVINCE 
    from "INTERVIEW_DB"."PLAYGROUND_DIGAMBER_KALIVEMULA"."COVID19_DATA" as data GROUP BY data.PROVINCE
)

select cases.CASE_RECOVERED_RATE, pro.TOTAL_REGENCIES, pro.TOTAL_CITIES from recovery_rate 
as cases INNER JOIN "INTERVIEW_DB"."PLAYGROUND_DIGAMBER_KALIVEMULA"."PROVINCES" as pro 
on pro.PROVINCE= cases.PROVINCE ORDER BY cases.CASE_RECOVERED_RATE